from django.db import models
from django.forms import CharField

# Create your models here.
'''
class ShortCourseMale(models.Model):
  freestyle_50 = CharField(max_length=5)
  freestyle_100 = CharField(max_length=7)
  freestyle_200 = CharField(max_length=7)
  freestyle_400 = CharField(max_length=7)
  freestyle_800 = CharField(max_length=7)
  freestyle_1500 = CharField(max_length=8)
  butterfly_50 = CharField(max_length=5)
  butterfly_100 = CharField(max_length=7)
  butterfly_200 = CharField(max_length=7)
  backstroke_50 = CharField(max_length=5)
  backstroke_100 = CharField(max_length=7)
  backstroke_200 = CharField(max_length=7)
  breaststroke_50 = CharField(max_length=5)
  breaststroke_100 = CharField(max_length=7)
  breaststroke_200 = CharField(max_length=7)
  im_100 = CharField(max_length=7)
  im_200 = CharField(max_length=7)
  im_400 = CharField(max_length=7)

class LongCourseMale(models.Model):
  freestyle_50 = CharField(max_length=5)
  freestyle_100 = CharField(max_length=7)
  freestyle_200 = CharField(max_length=7)
  freestyle_400 = CharField(max_length=7)
  freestyle_800 = CharField(max_length=7)
  freestyle_1500 = CharField(max_length=8)
  butterfly_50 = CharField(max_length=5)
  butterfly_100 = CharField(max_length=7)
  butterfly_200 = CharField(max_length=7)
  backstroke_50 = CharField(max_length=5)
  backstroke_100 = CharField(max_length=7)
  backstroke_200 = CharField(max_length=7)
  breaststroke_50 = CharField(max_length=5)
  breaststroke_100 = CharField(max_length=7)
  breaststroke_200 = CharField(max_length=7)
  im_200 = CharField(max_length=7)
  im_400 = CharField(max_length=7)

class ShortCourseFemale(models.Model):
  freestyle_50 = CharField(max_length=5)
  freestyle_100 = CharField(max_length=7)
  freestyle_200 = CharField(max_length=7)
  freestyle_400 = CharField(max_length=7)
  freestyle_800 = CharField(max_length=7)
  freestyle_1500 = CharField(max_length=8)
  butterfly_50 = CharField(max_length=5)
  butterfly_100 = CharField(max_length=7)
  butterfly_200 = CharField(max_length=7)
  backstroke_50 = CharField(max_length=5)
  backstroke_100 = CharField(max_length=7)
  backstroke_200 = CharField(max_length=7)
  breaststroke_50 = CharField(max_length=5)
  breaststroke_100 = CharField(max_length=7)
  breaststroke_200 = CharField(max_length=7)
  im_100 = CharField(max_length=7)
  im_200 = CharField(max_length=7)
  im_400 = CharField(max_length=7)

class LongCourseFemale(models.Model):
  freestyle_50 = CharField(max_length=5)
  freestyle_100 = CharField(max_length=7)
  freestyle_200 = CharField(max_length=7)
  freestyle_400 = CharField(max_length=7)
  freestyle_800 = CharField(max_length=7)
  freestyle_1500 = CharField(max_length=8)
  butterfly_50 = CharField(max_length=5)
  butterfly_100 = CharField(max_length=7)
  butterfly_200 = CharField(max_length=7)
  backstroke_50 = CharField(max_length=5)
  backstroke_100 = CharField(max_length=7)
  backstroke_200 = CharField(max_length=7)
  breaststroke_50 = CharField(max_length=5)
  breaststroke_100 = CharField(max_length=7)
  breaststroke_200 = CharField(max_length=7)
  im_200 = CharField(max_length=7)
  im_400 = CharField(max_length=7)
'''
