const clubs = [
  "",
  "AIL Skjetten SK",
  "Alta SK",
  "Andøya SLK",
  "Arendal SLK",
  "Arna SLK",
  "Asker SK",
  "Askimsvømmerne",
  "Askøy vannpoloklubb",
  "Aurland IL",
  "Aurskog/Finstadbru SK",
  "Austevoll IL",
  "Austrheim SK",
  "Averøy SK",
  "Bagn IL",
  "Bardufoss SK",
  "Bergen og Omegn Masters",
  "Bergen Paraidrettslag",
  "Bergen SLK",
  "Bergen Stupeklubb",
  "Bergen Triathlon Club",
  "Bergen Vannpoloklubb",
  "Bergen Vest SK",
  "Bergens SC",
  "Bergensvømmerne",
  "Bergkameratene",
  "Berlevåg TIF",
  "Bingsfoss Sportsklubb",
  "Bjerkvik SK",
  "Bjørkelangen SF",
  "Bjørn West IL",
  "Bodø SK",
  "Bodø Studentenes IL",
  "Brandbu IF",
  "Brattvåg SK",
  "Brevik IL",
  "Bryne SK",
  "Brønnøysund IL",
  "Bærum Stupklubb",
  "Bærumsvømmerne",
  "Bømlo SK",
  "Båtsfjord SK",
  "Christiania SK",
  "Daggry IL",
  "Delfana",
  "Dolphin Masters SK",
  "Dombås IL",
  "Dovrefjell SK",
  "Drag SK",
  "Drammen SK",
  "Drøbak-Frogn IL",
  "Egersund SK",
  "Eid SK",
  "Eidskog SK",
  "Eidsvoll SK",
  "Eikanger IL",
  "Elverum Svømming",
  "Etne SK",
  "Fagernes IL",
  "Falkeid IL",
  "Farsund SK",
  "Fauske SK",
  "Fedje IL",
  "Fet SK",
  "Finnsnes SK",
  "Fjaler SK",
  "Flekkefjord SK",
  "Flesberg SK",
  "Florø SK",
  "Foldereid IL",
  "Frisinn SK",
  "Frogner SK",
  "Froland SLG",
  "Fron SK",
  "Fræna SK",
  "Frøya IL",
  "Fusa SK",
  "Fyresdal IL",
  "Førde IL Symjing",
  "Gaular IL",
  "Gjelleråsen IF",
  "Gjerdrum IL",
  "Gjerstad IL",
  "Gjøvik SK",
  "Glitre SK",
  "Gol IL",
  "Gran IL",
  "Grimstad SK",
  "Haldens SK",
  "Halsnøy IL",
  "Hamar IL",
  "Hammerfest SLK",
  "Harestua IL",
  "Harstad SK",
  "Hasvik IL",
  "Haugesund SK",
  "Haugesund Triathlonklubb",
  "Havørn UIL",
  "Havøysund SK",
  "Heidal IL",
  "Hemnes IL",
  "Holmestrand IF",
  "Horten SK",
  "Husøy IL",
  "Hægebostad IL",
  "Høland IOU",
  "IL Bjørn",
  "IL Norodd",
  "IL Ros",
  "IL Skarphedin",
  "IL Solid",
  "IL Splint",
  "IL Tambar",
  "IL Trio",
  "IL Varg",
  "Indre Østfold SK",
  "Innstrandens IL",
  "Int. School of Stavanger",
  "Isbjørnan Masters SK",
  "Jotun IL",
  "Jægervatnet IL",
  "Jøa IL",
  "Jørpeland SK",
  "Karasjok SK",
  "Karmøy SK",
  "Kattem IL",
  "Kirkenes SK",
  "Kjøllefjord SK",
  "Klepp SSK",
  "Klæbu IL",
  "Kolbotn IL",
  "Kolvereid IL",
  "Kongstensvømmerne",
  "Kongsvinger SK",
  "Kragerø SK",
  "Kragerø Vannpoloklubb",
  "Kraken SK",
  "Kristiansand SA",
  "Kristiansand SK",
  "Kristiansand Stupeklubb",
  "Kristiansund SK",
  "Kråkstad IL",
  "Kvaløya SK",
  "Kvinesdal SK",
  "Kvæfjord SK",
  "Kyrksæterøra IL",
  "Lakselv SK",
  "Lambertseter SK",
  "Larvik HIL",
  "Larvik SK",
  "Leka IL",
  "Leksvik IL",
  "Levanger SLK",
  "Lier SK",
  "Lillehammer SK",
  "Lillesand IL",
  "Lund SK",
  "Lyngdal IL",
  "Lærdal IL",
  "Lørenskog/Rælingen",
  "Madla SK",
  "Malvik Helsesportlag",
  "Malvik IL",
  "Mandal SK",
  "Masters Sørlandet",
  "Melhus IL",
  "Meløy SK",
  "Misvær IL",
  "Modum SK",
  "Modum Triathlonklubb",
  "Molde SLK",
  "Mosjøen SK",
  "Moss SK",
  "Namsos SK",
  "Namsos Vannpoloklubb",
  "Nannestad IL",
  "Narvik SK",
  "Nedre Eiker SK",
  "Nedre Romerike HC IL",
  "Nes Svømmeklubb",
  "Nesna IL",
  "Nord/Sprint IL",
  "Nordby IL",
  "Nordkapp SK",
  "Nordre Land IL",
  "Nordreisa IL",
  "Nærbø SK",
  "Odal SK",
  "OI Svømming",
  "Orkanger IF",
  "Os SK",
  "Oslo Døves Sp.Kl.",
  "Oslo Politis IL",
  "Oslo Studentenes IK",
  "Oslo Stupeklubb",
  "Oslofjord triatlon",
  "Otta IL",
  "Overhalla IL",
  "Pingvin Stupklubb",
  "Politihøgskolens IL",
  "Poseidon",
  "Radøy SK",
  "Rana SK",
  "Randaberg IL",
  "Randaberg Stupe Klubb",
  "Randabergstuperne",
  "Raufoss IL",
  "Rena IL",
  "Ringerike SK",
  "Ringvassøy IL",
  "Riska SK",
  "Risør Varden",
  "Rjukan IL",
  "ROMA",
  "Rye sp.kl.",
  "Røa AIL",
  "Rørvik SLK",
  "Røyken HIL",
  "Samnanger IL",
  "Sandefjord SK",
  "Sandefjordstuperne",
  "Sandnes SLK",
  "Sandnessjøen IL",
  "Sarpsborg IL",
  "Setermoen SK",
  "Sjøstjerna SLK",
  "SK Speed",
  "SK Team Sør",
  "Skedsmo SK",
  "Ski SK",
  "Skien SK",
  "Skiptvet SLK",
  "Skjetten Svømming",
  "Skjåk IL",
  "Skånland SK",
  "Snøgg SK",
  "Sogndal IL",
  "Sola SK",
  "Sola TK",
  "Solund IL",
  "Solør SK",
  "Sortland SLK",
  "Sp. kl. Vats ",
  "Spinn",
  "Stange SK",
  "Stange Svømming",
  "Stathelle og Omegn IL",
  "Statland IL",
  "Stavanger HAIK",
  "Stavanger SK",
  "Stavanger Stupe Club",
  "Stavanger Vannpoloklubb",
  "Stegaberg IL",
  "Steinkjer SLK",
  "Stjørdals-Blink IL",
  "Stord Baby- og Barne SK",
  "Stord Masters SK",
  "Stord Symjing",
  "Stryn T og IL",
  "Sunde IL",
  "Sunndal SLK",
  "Svalbard Turn",
  "Svelgen TIF",
  "Svelvik SK",
  "Svolvær IL",
  "Sykkylven IL",
  "Søgne og Greipstad SK",
  "Søndre Høland IUL",
  "Sørreisa SK",
  "Sørumsand IF",
  "Sør-Varanger SK",
  "Sørvågen & Omegn IL",
  "T.I.L. Yngve KFUM Bergen",
  "Toten SK",
  "Triton Lillestrøm",
  "Tromsdalen KK",
  "Tromsø SK",
  "Tromsø Svømmeskole",
  "Tromsøstudentenes IL",
  "Trondheim HIL svømming",
  "Trondhjems SLK",
  "Trygg/Lade SK",
  "Tvedestrand Turn og IF",
  "Tverlandet IL",
  "Tynset IF",
  "Tysnes SK",
  "Tønsberg SK",
  "Ullensakersvømmerne",
  "Vadsø SK",
  "Valnesfjord IL",
  "Vardeneset IF",
  "Vardø SK",
  "Varodd SK",
  "Vega IL svømming",
  "Vennesla SK",
  "Verdal SK",
  "Vestby SLK",
  "Vestbyen Trondheim",
  "Vestkantsvømmerne",
  "Vika IF",
  "Vivil IL",
  "Volda TIL",
  "Voss IL",
  "Vågsbygd SLK",
  "Ytre Søre Sunnmøre SK",
  "Ølen IL",
  "Ørland SK",
  "Ørsta SK",
  "Øvre Eiker SK",
  "Øvre Romerike HIL",
  "Øyane SK",
  "Øygarden SK",
  "Ål IL",
  "Aalesunds SLK",
  "Ålgård SK",
  "Årdalstangen IL",
  "Ås IL",
  "Åstveit SK"
];

export default clubs;
