name: Build CI

on: [pull_request, push]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt update && sudo apt install node && npm install
    - name: build site
      run: npm run build
    - name: create exportable build
      run: npm run export