name: Build CI

on: [pull_request, push]

jobs:
  build:
  
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_PATH: /ntnui-swimming-frontend

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt update && sudo apt install npm && npm install
    - name: build site
      run: npm run build
    - name: create exportable build
      run: npm run export
    - name: Add .nojekyll file
      run: touch ./out/.nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages
        folder: out
