# Generated by Django 4.0.4 on 2022-04-18 10:15

import apps.enrollment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=6, validators=[apps.enrollment.models.validate_gender])),
                ('first_name', models.TextField()),
                ('surname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
                ('phone_domain', models.CharField(max_length=5)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
                ('zip', models.IntegerField()),
                ('licence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=6, validators=[apps.enrollment.models.validate_gender])),
                ('first_name', models.TextField()),
                ('surname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
                ('phone_domain', models.CharField(max_length=5)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
                ('zip', models.IntegerField()),
                ('licence', models.TextField()),
            ],
        ),
    ]
